base_url = "https://jade.fyi"

compile_sass = true

build_search_index = false

feed_filename = "rss.xml"
generate_feed = true

title = "jade's website"
description = "computers i guess"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
copyright = "(c) 2021 jade CC-BY-SA"
dtformat = "%B %d, %Y"
debug = false
