base_url = "https://jade.fyi"

compile_sass = true

build_search_index = false

feed_filename = "rss.xml"
generate_feed = true

title = "jade's www site"
description = "computers i guess"

[markdown]
highlight_code = true
extra_syntaxes = ["syntax"]

[extra]
# Put all your custom variables here
copyright = "(c) 2021 jade // all rights reserved"
dtformat = "%B %d, %Y"
debug = false
