base_url = "https://jade.fyi"

compile_sass = true

build_search_index = false

feed_filename = "rss.xml"
generate_feed = true

title = "jade's www site"
description = "computers i guess"

ignored_content = ["*/README.md"]

[markdown]
highlight_code = true
use_tree_painter = true
highlight_theme = "ayu_mirage_hacked"
extra_syntaxes_and_themes = ["syntax"]

[extra]
# Put all your custom variables here
copyright = "(c) 2022 jade // all rights reserved"
dtformat = "%B %d, %Y"
debug = false
